### ISSUE TITLE
bids2set resampling algorithm not working for data with fluid sampling rate

### ISSUE THREAD

**Issue by sjeung** [BeMoBIL/bemobil-pipeline#77]
Hi all, 

I am opening this issue to let people know that fluctuating sampling rate can be problematic for resampling algorithm.

We noticed that the bids2set import script's resampling algorithm for non-EEG data does not work well for data sets with a fluctuating sampling rate. 

This is caused by this line that assumes a sampling rate that is stable, i.e., samples should be evenly spaced throughout a single LSL recording.  

  DATA.times                  = DATA.times/srate_ratios(iSes,Ri);
  
For instance, if your sampling rate is 90 Hz for most of the time but drops down and leads to an effective sampling rate estimate of 82 Hz, this will cause the time stamps to be shifted in between. 

 
 I intend to circle back to this and submit a PR sometime soon. 
 In the meantime, in case you encounter a misalignment issue between motion and events after .set import, I recommend you to use a different means for time synching non-EEG data with EEG. 
e.g. directly using the time stamps of events from BIDS events.tsv and adding the offset stored in scans.tsv

**Comment by sjeung** [comment]
The issue was fixed by the PR above. Still unsure how the multiplication of time stamps by srate ratio contributes to better synchronization when offset may not be proportional to the time stamp values.  Also unsure if repo is planned to be maintained

**Comment by MariusKlug** [comment]
The srate ratios (lines 597 and 699, assigned in 348 and 446) are used to correct for small imprecisions in the sampling rate of the EEG. E.g. an EEG stream that has an srate of 1000Hz declared, but is sampled with 1000.02Hz in reality will lead to initially small, but after a while relevant shifts in relation to other data streams. So that's not an offset added as a constant shift, but it stretches the other data streams slightly to keep synchrony with the EEG data. This is because the EEG data has only post-hoc generated timestamps based on their nominal srate, not the effective srate or the real timestamps, and all streams are synched to that one EEG stream in EEGLAB in the end.

Regarding maintenance, at this point, I can not confidently say I can do this. I will answer urgent issues if they arise but I'm happy to pass the repo on.
